version: '3.8'

services:
    postgres-service:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=o5hapLMEM1
            - POSTGRES_DB=Testovoe
        networks:
            - testovoe

    history-service:
        build: ./historyService/
        restart: unless-stopped
        ports:
            - '3000:3000'
        networks:
            - testovoe
        depends_on:
            - postgres-service

    users-service:
        build: ./userService/
        ports:
            - '1337:1337'
        networks:
            - testovoe
        depends_on:
            - postgres-service

networks:
    testovoe:
        external: true
